import Head from "next/head";
import Title from "../components/Title";
import Link from "next/link";
import { getProducts } from "../lib/products";
import ProductCard from "../components/ProductCard";

export const getStaticProps = async () => {
  const products = await getProducts();
  return {
    props: {
      products,
    },
    revalidate: parseInt(process.env.REVALIDATE_SECONDS),
  };
};

export default function HomePage({ products }) {
  return (
    <>
      <Head>
        <title>Next Shop</title>
        <meta name="our shop" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-6 py-4">
        <Title>Next Shop</Title>
        <ul className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3">
          {products.map((product) => (
            <li key={product.id}>
              <ProductCard product={product} />
            </li>
          ))}
        </ul>
      </main>
    </>
  );
}
